name: my_app
description: Shop management
version: 1.0.4+9
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  animated_text_kit: ^4.2.3
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  dio: ^5.8.0+1
  dropdown_button2: ^2.3.9
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_slidable: ^3.1.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_typeahead: ^5.2.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  logger: ^2.5.0
  meta: ^1.15.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  stream_transform: ^2.1.1
  super_clipboard: ^0.8.24
  transparent_image: ^2.0.1
  upgrader: ^11.3.1

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: NotoSansKhmer
      fonts:
        - asset: fonts/NotoSansKhmer-Black.ttf
          weight: 900
        - asset: fonts/NotoSansKhmer-Bold.ttf
          weight: 700
        - asset: fonts/NotoSansKhmer-ExtraBold.ttf
          weight: 800
        - asset: fonts/NotoSansKhmer-ExtraLight.ttf
          weight: 200
        - asset: fonts/NotoSansKhmer-Light.ttf
          weight: 300
        - asset: fonts/NotoSansKhmer-Medium.ttf
          weight: 500
        - asset: fonts/NotoSansKhmer-Regular.ttf
          weight: 400
        - asset: fonts/NotoSansKhmer-SemiBold.ttf
          weight: 600
        - asset: fonts/NotoSansKhmer-Thin.ttf
          weight: 100
  assets:
    - .env
    - .env.dev
    - assets/
