name: my_app
description: Shop management
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  animated_text_kit: ^4.2.3
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.1.2
  get_it: ^8.0.3
  go_router: ^14.8.1
  http: ^1.3.0
  intl: ^0.19.0
  logger: ^2.5.0
  meta: ^1.15.0
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  transparent_image: ^2.0.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
  - .env
  - assets/
