# Fastlane for Android - run: cd android && bundle install && bundle exec fastlane <lane>
source "https://rubygems.org"
gem "fastlane"
gem "rake"

plugins_path = File.join(__dir__, "fastlane", "Pluginfile")
eval_gemfile(plugins_path) if File.exist?(plugins_path)
